### ISSUE TITLE
Site broken (Klipse doesn't run)

### ISSUE THREAD

**Issue by mchampine** [clojurebridge-course/clojurebridge-course.github.io#1]
Viebel says:
In the html of the pages, instead of `http://app.klipse.tech/plugin/js/klipse_plugin.js?v=1.9.0` you should have `https://app.klipse.tech/plugin/js/klipse_plugin.js?v=1.9.0` and instead of `http://app.klipse.tech/css/codemirror.css` you should have `https://app.klipse.tech/css/codemirror.css`

**Comment by jr0cket** [comment]
Thanks for the reminder.  This is an old experiment that didnt quite work and never got cleaned up.  We will remove the site.
